### ISSUE TITLE
should('be.colored', '#123123') throws error "CypressError: Timed out retrying: actual.equals is not a function"

### ISSUE THREAD

**Issue by chapati23** [cypress-io/cypress-example-recipes#102]
The `chai-colors` example in [this spec](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/extending-cypress__chai-assertions/cypress/integration/extending-chai-assertion-plugins-spec.js) doesn't work for me.

I'm getting an error `CypressError: Timed out retrying: actual.equals is not a function` which I assume is some error in integrating the `chai-colors` plugin.

This is my reduced test code:

```js
import chaiColors from 'chai-colors'
chai.use(chaiColors)
const URL = 'http://localhost:8080'

describe("Demo Test", () => {
  before(() => {
    cy.visit(`${URL}/`)
  })

  it('should work', () => {
      cy
        .get('#name')
        .siblings('p')
        .should('be.colored', '#F53D84')
  })
})
```

If I use the non-chai version it works as expected:

```js
const URL = 'http://localhost:8080'

describe("Demo Test", () => {
  before(() => {
    cy.visit(`${URL}/`)
  })

  it('should work', () => {
      cy
        .get('#name')
        .siblings('p')
        .should('have.css', 'color', 'rgb(245, 61, 132)')
  })
})
```

Any ideas what's going wrong here?

**Comment by jennifer-shehane** [comment]
Hey @chapati23, the example you pasted above errors because `chai-colors` expects a string to be passed along to the `be.colored` assertions. The `.siblings('p')` command you used will [yield a DOM element or elements](https://docs.cypress.io/api/commands/siblings.html#Yields). The `chai-colors` doesn't know what css attribute you are expecting to compare the color against. You need to dive into the css attribute you'd like to assert against. 

Here's an example that worked for me: 

```js
import chaiColors from 'chai-colors'
chai.use(chaiColors)

const URL = 'http://localhost:8484'

describe("Demo Test", () => {
  before(() => {
    cy.visit(`${URL}/`)
  })

  it('should work', () => {
      cy.get('.login-left')
        .should('have.css', 'background-color')
        .and('be.colored', '#17202c')
  })
})
```

<img width="807" alt="screen shot 2018-01-22 at 10 53 50 am" src="https://user-images.githubusercontent.com/1271364/35230058-0602cb8a-ff63-11e7-80bd-ac98f9840036.png">


I can see how our example is not very helpful though as it does not have an example of asserting colors of actual DOM elements. Perhaps we should open an issue to extend the example to include one.

**Comment by chapati23** [comment]
aaaaah, yeah i didn't get that from the example. i understood it that it's _either_ `should('have.css', etc)` (without `chai-colors` _or_ `should('be.colored', etc)` — chaining it indeed works for me. thanks!
