### ISSUE TITLE
Show recipe spying on console.* methods and asserting on them

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-example-recipes#11]
Also add this to the FAQ

**Comment by gabbersepp** [comment]
I take this one. 
One question regarding executing the tests:
On WIndows I can not execute "npm run cypress:open" within the example projects because the scripts use Linux command style. Is this a already known problem?
Maybe there is a solution for this. It is a bit annyoing if you want to start contributing and nothing works ;-P

**Comment by gabbersepp** [comment]
@jennifer-shehane Are the examples sufficient? If yes, this issue could be closed I think
