### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by malmuzaini** [cypress-io/cypress-example-recipes#146]
I am trying to stub fetch on the application I am testing so I can stub the response of fetch, but I am getting this error!

**Comment by brian-mann** [comment]
This is almost certainly due to you not properly stubbing `fetch`. Whenever you stub out a function, the default in sinon is to return `undefined` if you also supplied `withArgs` and the function was not called with those args.

You just need to step through and debug what is calling `fetch` and whether or not its called with the right arguments.

There is no way we can be of any help without you posting code or making an effort to debug what's going on.
