### ISSUE TITLE
Drag and Drop won't work as expected.

### ISSUE THREAD

**Issue by nitingupta220** [cypress-io/cypress-example-recipes#202]
I'm using angular drag-drop which under the hood is using Jquery UI Draggable to handle drag and drop.
I want to take one element and drag it to my targeted element. But I won't be able to do it.
In the task runner, it shows that the element is moving but it is not dropping to the targeted element.
```
cy.login()
cy.get('.possibility-resp-list-container .drag-btn').contains('A')
    .trigger('mousedown', { which: 1, pageX: 600, pageY: 100 })
cy.get('.cyClassify table td.drop-zone-multiple').first()
    .trigger('mousemove')
    .trigger('mouseup')
```

Please help. @jennifer-shehane @brian-mann @frazboyz

**Comment by jmcollin78** [comment]
I've tried many workaround (the drag and drop plugin for example) but the only working solution is here : https://stackoverflow.com/questions/55361499/how-to-implement-drag-and-drop-in-cypress-test see @Bkucera solution.

**Comment by jennifer-shehane** [comment]
Issues in this GitHub repo is reserved for adding or requesting cypress recipes. This issue will be closed since it appears to be a question.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by jmcollin78** [comment]
Hi @jennifer-shehane , it is not a question since Drag And Drop is not working out the box. Moreover, you get an answer in my previous post to make it works as expected
