### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress-example-recipes#3]
I was wondering if Cypress had a recommended tool for calculating code coverage? and if so are there any examples?

**Comment by brian-mann** [comment]
Closing in favor of opening this in the main repo for discussion.

There is no way to put a recipe of this because code coverage is very complicated and would have to exist at the main process level, not just something magically done at the spec level.

The strategies involving `unit` vs `e2e` tests are completely different and there is no simple `node_module` or anything to install.

**Comment by kiwi6787999okojj** [comment]
#346 Code Coverage in cypress-io/cypress
