### ISSUE TITLE
Stubs all fetch or just the ones that match `withArgs`

### ISSUE THREAD

**Issue by DannyAziz** [cypress-io/cypress-example-recipes#321]
So I'm trying to stub a network request withArgs `/register` but I get an error `Cannot read property 'then' of undefined` because of another network request that is being stubbed but doesn't match the args I passed to `withArgs`

Is there a way to let network requests that don't match `withArgs` still call through? I saw the `callThrough` function on Sinon but am having difficulty getting it to work

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repos are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our [premium support options](https://www.cypress.io/support/).
