### ISSUE TITLE
Ignore before/after methods

### ISSUE THREAD

**Issue by cooleiwhistles** [cypress-io/cypress-example-recipes#338]
I was trying to use this plugin for my cypress testing, but noticed it was failing the data teardown we have setup in afterMethod of tests not tagged with our grep expression. Is there a known way to exclude these from being ran if not associated with the test spec that is ran using with grep config?

**Comment by jennifer-shehane** [comment]
This is not a plugin, this is an example repo containing tests to run on a test website. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

I'd suggest asking questions on how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).
