### ISSUE TITLE
cy.task() does not work with node 8+

### ISSUE THREAD

**Issue by ronaiza-cardoso** [cypress-io/cypress-example-recipes#347]
In my server I'm using things like `async/await`, `import/export`, etc and even when implementing what are showing in this [exemple](https://github.com/cypress-io/cypress-example-recipes/pull/120) I still get this error: https://github.com/cypress-io/cypress/issues/3198#issuecomment-543128220

**Comment by bahmutov** [comment]
This is because Cypress tasks run in the Node 8.9.3 that is currently bundled with Cypress application, and thus do not match the Node 10+ that your sql driver requires. Soon you will be able to run tasks using system Node version, watch this pull request to be merged and released: https://github.com/cypress-io/cypress/pull/4436
