### ISSUE TITLE
Link from tab_handling_anchor_links_spec.js to stubbing-spying__window

### ISSUE THREAD

**Issue by NotSoImportant** [cypress-io/cypress-example-recipes#423]
1) Please create a linkage between [tab_handling_anchor_links_spec.js](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__tab-handling-links/cypress/integration/tab_handling_anchor_links_spec.js) and [stubbing-spying__window](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__window/cypress/integration/spec.js).
Both are tackeling the same problem.

2) Please explain what method is the better approach (if generally possible) or give some hints why/when this or that should be used.

Thank you

**Comment by dburugupalli** [comment]
@jennifer-shehane  I think that the solution 4 is good approach. Because, it helps to reduce the browser load time. In addition, it checks the website by requesting the content and also helps in verifying the various parameters to test aganist

Are you expecting a code from tab_handling_anchor_links_spec,js to stubbing-spying__window.js?
as per any of the correct solution. ?
