### ISSUE TITLE
hover on shadow dom elements

### ISSUE THREAD

**Issue by rameshrc** [cypress-io/cypress-example-recipes#525]
I have an application that is made of web components with lit-html. I could not make hover to work with the help of invoke or trigger along with experimental shadow dom as true. 
Also, I dont see CRI mode working .
Any suggestions?

**Comment by jennifer-shehane** [comment]
Issues in this GitHub repo are reserved for kitchensink examples. This issue will be closed since it appears to not be related to kitchensink examples.

If you can provide a fully reproducible example of this not working - showing this is a bug in Cypress, please open it in the main repo. 

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
