### ISSUE TITLE
Unable to close PopUp Alert or unable to click ok button in any alert popup in cypress

### ISSUE THREAD

**Issue by agrmayank03** [cypress-io/cypress-example-recipes#544]
```js
iframepage.switch('#_bmain').xpath("user name").type('')
iframepage.switch('#_bmain').xpath("password").type('')
iframepage.switch('#_bmain').xpath("login button").click()
```
after login this, a popup alert message with OK button is coming which is not closing automatically and i am unable to close it with any manual code.. (we can't inspect the coming popup)

Example , i used below codes:

1.
```js
cy.on('window:alert', msg => alerted = msg);
    cy.get('button').contains('OK').click()
```

2. 
```js
Cypress.on('window:load', function(window) {
      const original = window.addEventListener;
      window.addEventListener = function() {
          if (arguments && arguments[0] === 'onbeforeunload') {
              return;
          }
          return original.apply(this, arguments);
      };
  })
```

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
