### ISSUE TITLE
File download triggers page load wait

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-recipes#565]
Seems to trigger `onBeforeUnload` event callback. 

In a separate company project, as reported by the user, clicking on the `a` link downloads the file _and_ starts page load which times out.

Markup

<img width="749" alt="Screen Shot 2020-09-14 at 11 56 34 AM" src="https://user-images.githubusercontent.com/2212006/93108941-70172300-f681-11ea-8afd-f5afa3bd0479.png">

Note that the file is from another domain

Callstack

<img width="1389" alt="Screen Shot 2020-09-14 at 11 54 18 AM" src="https://user-images.githubusercontent.com/2212006/93108799-3d6d2a80-f681-11ea-8249-f2a690048ab0.png">

**Comment by bahmutov** [comment]
Can we recreate this issue?

**Comment by Bkucera** [comment]
the `download` attribute has no affect here since it's cross-origin. I believe the browser is simply navigating to the csv file and the default behavior is to download it. If you had a cross-origin png, the file wouldn't be downloaded since the browser's default is to view it.

Since this is actually a page navigation and not a download, there's not a good solution here

**Comment by bahmutov** [comment]
Good answer @Bkucera - that settles it enough
